-include .env


deploy-sepolia: 
	forge scrept script/DeployFundMe.sol:DeployFundme 
	--rpc-url $(SEPOLIA_RPC_URL) 
	--private-key  $(PRIVATE_KEY) 
	--etherscan-api-key $(ETHERSCAN_API_KEY)
	--broadcast 
	--vvvv

